### ISSUE TITLE
Questionable license

### ISSUE THREAD

**Issue by jfrech** [davidhampgonsalves/foxish#11]
How can _foxish_ be [licensed under MIT](https://github.com/davidhampgonsalves/foxish/blob/master/LICENSE) when its source code contains lines like the following?
https://github.com/davidhampgonsalves/foxish/blob/e008ce3c7d088536d9dcef93b20685c79b741659/subscribe.html#L3-L5

**Comment by davidhampgonsalves** [comment]
Poorly apparently. The license was added after the fact and I didn't remember that it does contain that code from Googles RSS reader. So the Foxish code is MIT and the Google code is BSD.

If anyone wants alternate licensing let me know.
