### ISSUE TITLE
Extension page gives 404

### ISSUE THREAD

**Issue by benjaminoakes** [davidhampgonsalves/foxish#13]
https://chrome.google.com/extensions/detail/jpgagcapnkccceppgljfpoadahaopjdb currently results in a 404

That's too bad because I liked this extension.  If nothing else, consider this post a thank you for releasing and maintaining it.

**Comment by davidhampgonsalves** [comment]
Yea, sorry it was taken down by Google. I don't currently use chrome so it'll stay like that for the foreseeable future.

**Comment by davidhampgonsalves** [comment]
I fixed this and resubmitted - https://chrome.google.com/webstore/detail/foxish-live-rss/nbhdikhnaigcdlamenbgkmllgmfnngoi

**Comment by benjaminoakes** [comment]
Wonderful, thank you!
