### ISSUE TITLE
Show full title in hover baloon

### ISSUE THREAD

**Issue by DenisBY** [davidhampgonsalves/foxish#3]
Is it possible to improve extension to show full title in hover balloon like in FF?
In FF:
![image](https://user-images.githubusercontent.com/1147703/30276129-1bbd8e82-9704-11e7-8d1b-612636763f70.png)
In Foxish:
![image](https://user-images.githubusercontent.com/1147703/30276144-25f027c0-9704-11e7-812d-f236ad36b32c.png)

**Comment by davidhampgonsalves** [comment]
Sorry Chrome doesn't allow for these kinds of customisations.
