### ISSUE TITLE
Three little problems and / or requests

### ISSUE THREAD

**Issue by dergilb99** [davidhampgonsalves/foxish#4]
First of all, thank you for Foxish Live RSS!

I only have three little problems and / or requests:

1. I'm using Vivaldi and here hovering from one feed to another feed is not working (click on feed 1 on bookmark bar, then move the cursor to feed 2.) This works in Chrome, but not in Vivaldi (feed 1 will stay open instead of showing the second feed). Here you have to click on each feed. Which is quite some clicking when checking multiple feeds.
2. The folder icon looks not very RSSish. So it's a bit hard to distinguish bookmark folder and RSS feeds. What about switching the folder icon with an RSS icon or favicon?
3. (Some simple visual info if there are new feeds, maybe? Like a lighter RSS icon folder when there's nothing new vs. a darker one if there were new feeds within the last x minutes?)

Have a nice day!

**Comment by davidhampgonsalves** [comment]
Sorry, Chrome doesn't allow for these kinds of customisations.
